Source/AdsVenture.Presentation.ContentServer/Models/Shared/ConfirmModal.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AdsVenture.Presentation.ContentServer.Models.Shared
{
    public class ConfirmModal
    {
        public string ID { get; set; }
        public string Title { get; set; }
        public string Question { get; set; }
        public string OnConfirm { get; set; }
    }
}

Source/AdsVenture.Presentation.ContentServer/Models/Shared/DatePicker.cs
using HtmlTags;
using System;

namespace AdsVenture.Presentation.ContentServer.Models.Shared
{
    public class DatePicker
    {
        public bool AppendCalendarMode { get; set; }
        public bool Disabled { get; set; }
        public MinViewModes MinViewMode { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }

        public HtmlTag TextBoxTag { get; set; }

        public enum MinViewModes
        {
            Days,
            Months,
            Years
        }
    }
}

Source/AdsVenture.Presentation.ContentServer/Models/Shared/FileUpload.cs
using HtmlTags;

namespace AdsVenture.Presentation.ContentServer.Models.Shared
{
    public class FileUpload
    {
        public string ID { get; set; }
        public string Url { get; set; }
        public string UrlFieldName { get; set; }
        public string IsEmptyFieldName { get; set; }
        public HtmlTag TextBoxTag { get; set; }
    }
}

Source/AdsVenture.Presentation.ContentServer/Models/Shared/MassiveParams.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AdsVenture.Presentation.ContentServer.Models.Shared
{
    // <summary>
    // This class is used for posting an array of IDs to a WebApi action
    // </summary>
    public class MassiveParams<TId>
    {
        public TId[] IDs { get; set; }
    }

    // <summary>
    // This class is used for posting an array of IDs to a WebApi action
    // </summary>
    public class MassiveParams : MassiveParams<int>
    {
    }
}

Source/AdsVenture.Presentation.ContentServer/Models/Shared/ShortListItem.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AdsVenture.Presentation.ContentServer.Models.Shared
{
    public class ShortListItem
    {
        public int ID { get; set; }
        public string Description { get; set; }
    }
}

Source/AdsVenture.Presentation.ContentServer/Controllers/AdvertisersController.cs
using AdsVenture.Commons.Pagination;
using AdsVenture.Core.Managers;
using AutoMapper;
using Bardock.Utils.Extensions;
using Bardock.Utils.Web.Mvc.HtmlTags;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace AdsVenture.Presentation.ContentServer.Controllers
{
    public class AdvertisersController : _BaseController
    {
        private readonly AdvertiserManager _manager;
        private readonly CountryManager _countryManager;

        public AdvertisersController(
            AdvertiserManager mediagroupmanager, 
            CountryManager countryManager)
        {
            this._manager = mediagroupmanager;
            this._countryManager = countryManager;
        }

        public ActionResult Index()
        {
            ViewBag.AddPathNodeWithTitle = Resources.Global.Search;
            return View();
        }

        public ActionResult Index_Table(PageParams pageParams)
        {
            return TablePage(_manager.FindAll(pageParams));
        }

        public ActionResult Add()
        {
            return GetAddView();
        }

        private ActionResult GetAddView(Commons.Entities.Advertiser e = null)
        {
            return GetFormView(e, isNew: true);
        }

        [HttpPost]
        public ActionResult Add(Core.DTO.AdvertiserCreate data)
        {
            try
            {
                _manager.Create(data);
                Notifications.AddSuccess(Commons.Resources.Shared.Success_Add);
                return RedirectToControllerHome();
            }
            catch (Core.Exceptions.BusinessUserException ex)
            {
                Notifications.AddError(ex.Message);
            }
            catch (Core.Exceptions.BusinessException)
            {
                Notifications.AddError(Commons.Resources.Shared.Error_Undefined);
            }
            return GetAddView(Mapper.Map<Commons.Entities.Advertiser>(data));
        }

        public ActionResult Edit(Guid id)
        {
            return GetEditView(id);
        }

        private ActionResult GetEditView(Guid id, Core.DTO.AdvertiserUpdate data = null)
        {
            var e = _manager.Find(id);

            if (e == null)
            {
                ThrowHttpNotFound();
            }
            
            ViewBag.AddPathNodeWithTitle = e.Name;

            if(data != null)
            { 
                e = Mapper.Map(data, e);
            }
            return GetFormView(e);
        }

        [HttpPost]
        public ActionResult Edit(Core.DTO.AdvertiserUpdate data)
        {
            try
            {
                _manager.Update(data);
                Notifications.AddSuccess(Commons.Resources.Shared.Success_Update);
                return RedirectToControllerHome();
            }
            catch (Core.Exceptions.BusinessUserException ex)
            {
                Notifications.AddError(ex.Message);
            }
            catch (Core.Exceptions.BusinessException)
            {
                Notifications.AddError(Commons.Resources.Shared.Error_Undefined);
            }
            return GetEditView(data.ID, data);
        }

        private ActionResult GetFormView(Commons.Entities.Advertiser e = null, bool isNew = false)
        {
            var model = new Models.Advertisers.Form()
            {
                IsNew = isNew,
                CountryOptions = OptionsList.Create(_countryManager.FindAll(), display: x => x.Description, value: x => x.ID),
                Entity = e
            };
            return View("Form", model);
        }
    }
}

Source/AdsVenture.Presentation.ContentServer/Views/Shared/_ConfirmModal.cshtml
@model AdsVenture.Presentation.ContentServer.Models.Shared.ConfirmModal

<div id="@Model.ID" class="modal" data-backdrop="true" tabindex="-1" role="dialog" aria-labelledby="modal_confirm_title" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h3 id="modal_confirm_title">@Model.Title</h3>
            </div>
            <div class="modal-body">
                <p>@Model.Question</p>
                <div class="confirm-description">
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btnConfirm btn-primary pull-left" onclick="@Model.OnConfirm" data-dismiss="modal" aria-hidden="true">
                    @Resources.Global.Accept
                </button>
                <button class="btn btn-link btn_negative pull-left" data-dismiss="modal" aria-hidden="true">
                    @Resources.Global.Cancel
                </button>
            </div>
        </div>
    </div>
</div>

Source/AdsVenture.Presentation.ContentServer/Views/Shared/_DatePicker.cshtml
@using Bardock.Utils.Extensions
@model AdsVenture.Presentation.ContentServer.Models.Shared.DatePicker

<div class="input-append inline date datepicker-component @(Model.AppendCalendarMode ? "append_calendar" : String.Empty) @(Model.Disabled ? "disabled" : String.Empty)"
     data-date-format="@DateExtensions.CurrentDateFormat().ToLower()"
     data-date-min-view-mode="@Model.MinViewMode.ToString().ToLower()"
     data-date-startdate="@Model.StartDate.ApplyOrDefault(x => x.DateFormat())"
     data-date-enddate="@Model.EndDate.ApplyOrDefault(x => x.DateFormat())">

    @Model.TextBoxBuilder(new Dictionary<string, object>() {
                            {"class", "input-small " + Model.InputClass},
                            {"readonly", "readonly"}
                          })

    <span class="add-on @(Model.Disabled ? "disabled" : String.Empty)">
        <i class="icon-calendar icon-white"></i>
    </span>
</div>

Source/AdsVenture.Presentation.ContentServer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>@(ViewBag.Title ?? Html.GetViewTitle()) :: PLG</title>

    @Styles.Render("~/Content/css/site")

    <!--[if lt IE 9]>
        <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
</head>
<body>

    @Html.MvcSiteMap().Menu()
    @Html.MvcSiteMap().SiteMapPath()

    <div class="container body-content">

        @Html.Partial("~/Views/Shared/_Notifications.cshtml")

        @RenderBody()

    </div>

    @RenderSection("modals", required: false)

    @******* SCRIPTS *******@

    @Scripts.Render("~/bundles/site")
    <script>
    var Resources = {
        DataTables: {
            "sProcessing":     "@Html.Raw(Resources.DataTables.Processing)",
            "sLengthMenu":     "@Html.Raw(Resources.DataTables.LengthMenu)",
            "sZeroRecords":    "@Html.Raw(Resources.DataTables.ZeroRecords)",
            "sEmptyTable":     "@Html.Raw(Resources.DataTables.EmptyTable)",
            "sInfo":           "@Html.Raw(Resources.DataTables.Info)",
            "sInfoEmpty":      "@Html.Raw(Resources.DataTables.InfoEmpty)",
            "sInfoFiltered":   "@Html.Raw(Resources.DataTables.InfoFiltered)",
            "sSearch":         "@Html.Raw(Resources.DataTables.Search)",
            "sInfoThousands":  "@Html.Raw(Resources.DataTables.InfoThousands)",
            "sLoadingRecords": "@Html.Raw(Resources.DataTables.LoadingRecords)",
            "oPaginate": {
                "sFirst":    "@Html.Raw(Resources.DataTables.Paginate_First)",
                "sLast":     "@Html.Raw(Resources.DataTables.Paginate_Last)",
                "sNext":     "@Html.Raw(Resources.DataTables.Paginate_Next)",
                "sPrevious": "@Html.Raw(Resources.DataTables.Paginate_Previous)"
            },
            "oAria": {
                "sSortAscending":  "@Html.Raw(Resources.DataTables.Aria_SortAscending)",
                "sSortDescending": "@Html.Raw(Resources.DataTables.Aria_SortDescending)"
            }
        },
        Success_Add: "@Html.Raw(AdsVenture.Commons.Resources.Shared.Success_Add)",
        Success_Delete: "@Html.Raw(AdsVenture.Commons.Resources.Shared.Success_Delete)",
        Success_Update: "@Html.Raw(AdsVenture.Commons.Resources.Shared.Success_Update)",
        Error_Undefined: "@Html.Raw(AdsVenture.Commons.Resources.Shared.Error_Undefined)",
        Error_Forbidden: "@Html.Raw(AdsVenture.Core.Resources.BusinessExceptions.UnauthorizedException)",
        Error_MustSelectAnyItem: "@Html.Raw(AdsVenture.Commons.Resources.Shared.Error_MustSelectAnyItem)"
    };
    var app = new App(
        $.extend(
            @Html.Json(Html.Config()), {
                baseUrl: "@Url.Content("/")",
                previousUrl: "@Url.PreviousLocal()",
                lang: "en",
                numbersFormat: {
                    currencyDecimals: "@DecimalFormatExtensions.CurrentFormatInfo.CurrencyDecimalDigits",
                    accurateDecimals: "@DecimalFormatExtensions.AccurateDecimals",
                    minDecimalsAfterSep: "@DecimalFormatExtensions.MinDecimalsAfterSeparator",
                    decimalSep: "@DecimalFormatExtensions.CurrentFormatInfo.NumberDecimalSeparator"
                }
            }
        )
    );
    </script>
    @RenderSection("scripts", required: false)
</body>
</html>

Source/AdsVenture.Presentation.ContentServer/Views/Shared/_NavigationMenu.cshtml
@using AdsVenture.Commons.Security.AccessControl
@using AdsVenture.Commons.Resources
@using Bardock.Utils.Web.Mvc.Extensions
<ul class="nav span11">
    @if (this.IsAuthorized<ProgramUpload>(Actions.Read) || this.IsAuthorized<ProgramUpload>(Actions.Create)
        || this.IsAuthorized<ProgramBroadcast>(Actions.Read) || this.IsAuthorized<ProgramRating>(Actions.Read))
    {
        <li class="dropdown @((this.IsController("programUploads") || this.IsController("programBroadcasts") || 
                this.IsController("programRatings")) ? "active" : String.Empty)">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">@Shared.ProgramsRating <b class="caret"></b></a>
            <ul class="dropdown-menu">
                @if (this.IsAuthorized<ProgramUpload>(Actions.Read) && this.IsAuthorized<ProgramUpload>(Actions.Create))
                {
                    <li><a href="@Url.Action("Index", "programUploads")">@Shared.Files</a></li>
                }
                @if (this.IsAuthorized<ProgramBroadcast>(Actions.Read))
                {
                    <li><a href="@Url.Action("Index", "programBroadcasts")">@Shared.Programming</a></li>
                }
                @if (this.IsAuthorized<ProgramRating>(Actions.Read))
                {
                    <li><a href="@Url.Action("Index", "programRatings")">@Shared.Ratings</a></li>
                }
            </ul>
        </li>
    }
    @if (this.IsAuthorized<ChannelUpload>(Actions.Read) || this.IsAuthorized<ChannelUpload>(Actions.Create)
        || this.IsAuthorized<ChannelNetwork>(Actions.Read) || this.IsAuthorized<Advertiser>(Actions.Read)
        || this.IsAuthorized<Advertiser>(Actions.Create) || this.IsAuthorized<ChannelRating>(Actions.Read))
    {
        <li class="dropdown @((this.IsController("channelUploads") || this.IsController("channelMediaGroups") || 
                this.IsController("channelRatings") || this.IsController("channelNetworks") || 
                this.IsController("channelReports")) ? "active" : String.Empty)">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">@Shared.ChannelsRating <b class="caret"></b></a>
            <ul class="dropdown-menu">
                @if (this.IsAuthorized<ChannelUpload>(Actions.Read) && this.IsAuthorized<ChannelUpload>(Actions.Create))
                {
                    <li><a href="@Url.Action("Index", "channelUploads")">@Shared.Files</a></li>
                }
                @if (this.IsAuthorized<ChannelRating>(Actions.Read))
                {
                    <li><a href="@Url.Action("Index", "channelRatings")">@Shared.Ratings</a></li>
                }
                @if (this.IsAuthorized<ChannelNetwork>(Actions.Read) && this.IsAuthorized<ChannelNetwork>(Actions.Create))
                {
                    <li><a href="@Url.Action("Index", "ChannelNetworks")">@Shared.Networks</a></li>
                }
                @if (this.IsAuthorized<Advertiser>(Actions.Read) && this.IsAuthorized<Advertiser>(Actions.Create))
                {
                    <li><a href="@Url.Action("Index", "Advertisers")">@Shared.MediaGroups</a></li>
                }
                @if (this.IsAuthorized<ChannelRating>(Actions.Read))
                {
                    <li class="dropdown-submenu @(this.IsController("channelReports") ? "active" : String.Empty)">
                        <a href="@Url.Action("index", "channelReports")" class="dropdown-toggle" data-toggle="dropdown">@Shared.Reports</a>
                        <ul class="dropdown-menu">
                            <li><a href="@Url.Action("TopChannels", "channelReports")">@Shared.TopChannels</a></li>
                            <li><a href="@Url.Action("MediaGroupRatings", "channelReports")">@Shared.MediaGroupRatings</a></li>
                        </ul>
                    </li>
                }
            </ul>
        </li>
    }
</ul>

Source/AdsVenture.Presentation.ContentServer/Views/Shared/_Notifications.cshtml
<div id="notifications">
    <script id="notifications-template" type="text/html">
        <div id="{{notificationId}}" class="alert alert-{{level}}">
            <button type="button" class="close" data-dismiss="alert">×</button>
            <p>{{message}}</p>
        </div>
    </script>
    <script id="notifications-template-linkedid" type="text/html">
        <div id="{{notification-id}}" class="alert alert-{{level}}">
            <button type="button" class="close" data-dismiss="alert">×</button>
            <p>{{message}} (ID: <a href="{{url}}">{{id}}</a>)</p>
        </div>
    </script>
    <script>
        var notifications_init = @Html.Json(Bardock.Utils.Web.RequestNotifications.Instance.Items.ToUIModel().ToArray());
    </script>
</div>